### ISSUE TITLE
Support Spring 6 / Spring Boot 3

### ISSUE THREAD

**Issue by stickfigure** [mapstruct/mapstruct-spring-extensions#109] opened 2024-07-17 19:01 UTC
This project seems to only generate `javax.annotation.PostConstruct` annotations. Those annotations have no effect in Spring 6 (ie Spring Boot 3). Spring 6 only pays attention to `jakarta.annotation.PostConstruct`.

**Comment by Chessray** [comment] 2024-07-17 19:03
Duplicate of #105

**Closed by Chessray** 2024-07-17 19:03 UTC
Labels: duplicate
